<?php

	/**
	 * Autogenerated module GroupedModules
	 *
	 * @author
	 * @version 0.1
	 * @license http://www.opensource.org/licenses/mozilla1.1.php Mozilla Public License 1.1 (MPL 1.1)
	 * @package groupedmodules
	 * @subpackage core
	 */

	/**
	 * Autogenerated module GroupedModules
	 *
	 * @package groupedmodules
	 * @subpackage core
	 */
    
    /**
     * @Table(name="TBGModulesTable")
     */
	class GroupedModules extends TBGModule
	{

		protected $_longname = 'Team Groups';
        
        protected $_description = 'Enables grouping of teams';
        
        protected $_module_config_title = 'Team Groups';
        
        protected $_module_config_description = 'Enables grouping of teams';
        
        protected $_has_account_settings = true;

        protected $_has_config_settings = true;
        
        protected $_module_version = '0.1';

        protected $mailer = null;
        
		/**
		 * Return an instance of this module
		 *
		 * @return GroupedModules
		 */
		public static function getModule()
		{
			return TBGContext::getModule('groupedmodules');
		}

		protected function _initialize()
		{
			
		}

		protected function _addAvailablePermissions()
		{
		}

		protected function _addAvailableListeners()
		{
		}

		protected function _addRoutes()
		{
            $this->addRoute('groupedmodules_index', '/groupedmodules', 'index');
		}

		protected function _install($scope)
		{
		}

		protected function _loadFixtures($scope)
		{
		}

		protected function _uninstall()
		{
		}

		public function getRoute()
		{
			return TBGContext::getRouting()->generate('groupedmodules_index');
		}

	}

